// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const getNotificationRefByMessage = `-- name: GetNotificationRefByMessage :one
SELECT kind, event_id FROM notification_refs
WHERE provider = $1 AND message_ref = $2
LIMIT 1
`

type GetNotificationRefByMessageParams struct {
	Provider   string
	MessageRef string
}

type GetNotificationRefByMessageRow struct {
	Kind    string
	EventID uuid.UUID
}

func (q *Queries) GetNotificationRefByMessage(ctx context.Context, arg GetNotificationRefByMessageParams) (GetNotificationRefByMessageRow, error) {
	row := q.db.QueryRow(ctx, getNotificationRefByMessage, arg.Provider, arg.MessageRef)
	var i GetNotificationRefByMessageRow
	err := row.Scan(&i.Kind, &i.EventID)
	return i, err
}

const getNotificationRefs = `-- name: GetNotificationRefs :many
SELECT provider, chat_ref, message_ref
FROM notification_refs
WHERE kind = $1 AND event_id = $2
`

type GetNotificationRefsParams struct {
	Kind    string
	EventID uuid.UUID
}

type GetNotificationRefsRow struct {
	Provider   string
	ChatRef    string
	MessageRef string
}

func (q *Queries) GetNotificationRefs(ctx context.Context, arg GetNotificationRefsParams) ([]GetNotificationRefsRow, error) {
	rows, err := q.db.Query(ctx, getNotificationRefs, arg.Kind, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationRefsRow
	for rows.Next() {
		var i GetNotificationRefsRow
		if err := rows.Scan(&i.Provider, &i.ChatRef, &i.MessageRef); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveNotificationRef = `-- name: SaveNotificationRef :exec
INSERT INTO notification_refs (kind, event_id, provider, chat_ref, message_ref)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (kind, event_id, provider)
DO UPDATE SET chat_ref = EXCLUDED.chat_ref, message_ref = EXCLUDED.message_ref, created_at = now()
`

type SaveNotificationRefParams struct {
	Kind       string
	EventID    uuid.UUID
	Provider   string
	ChatRef    string
	MessageRef string
}

func (q *Queries) SaveNotificationRef(ctx context.Context, arg SaveNotificationRefParams) error {
	_, err := q.db.Exec(ctx, saveNotificationRef,
		arg.Kind,
		arg.EventID,
		arg.Provider,
		arg.ChatRef,
		arg.MessageRef,
	)
	return err
}
